# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15v5DCA21eLxml-56OF9cXdPdwwSIDTou
"""

!pip install requests solana

import requests

# Récupérer les 10 premières cryptomonnaies par capitalisation de marché
url = 'https://api.coingecko.com/api/v3/coins/markets'
params = {
    'vs_currency': 'usd',
    'order': 'market_cap_desc',
    'per_page': 10,  # Nombre de cryptomonnaies
    'page': 1
}

response = requests.get(url, params=params)
data = response.json()

# Afficher les 10 meilleures cryptos
for coin in data:
    print(f"{coin['name']} ({coin['symbol'].upper()}): ${coin['current_price']}")

!pip install streamlit

import streamlit as st
import requests

# Récupération des données via l'API CoinGecko
url = "https://api.coingecko.com/api/v3/coins/markets"
params = {
    "vs_currency": "usd",
    "order": "market_cap_desc",
    "per_page": 10,
    "page": 1
}

response = requests.get(url, params=params)
data = response.json()

# Titre du Dashboard
st.title("Top 10 Cryptomonnaies")

# Tableau avec les données des cryptomonnaies
st.write("Voici la liste des 10 meilleures cryptomonnaies par capitalisation boursière :")

# Créer un tableau avec les informations
table_data = []
for coin in data:
    table_data.append([coin['name'], coin['current_price'], coin['market_cap'], coin['symbol']])

# Affichage sous forme de tableau
st.write("Les 10 meilleures cryptomonnaies")
st.table(table_data)